# Generated by Django 5.1.15 on 2026-10-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_name', models.CharField(max_length=255)),
                ('pickup_name', models.CharField(max_length=255)),
                ('dropoff_name', models.CharField(max_length=255)),
                ('initial_cycle_used', models.FloatField(default=0.0)),
                ('total_distance_miles', models.FloatField(default=0.0)),
                ('total_driving_hours', models.FloatField(default=0.0)),
                ('total_on_duty_hours', models.FloatField(default=0.0)),
                ('total_sleeper_hours', models.FloatField(default=0.0)),
                ('total_off_duty_hours', models.FloatField(default=0.0)),
                ('total_trip_days', models.IntegerField(default=1)),
                ('fuel_stops_count', models.IntegerField(default=0)),
                ('rest_stops_count', models.IntegerField(default=0)),
                ('carrier_name', models.CharField(default='Spotter Freight Lines Inc.', max_length=255)),
                ('truck_number', models.CharField(default='TRK-4091', max_length=50)),
                ('trailer_number', models.CharField(default='TLR-8820', max_length=50)),
                ('summary_data', models.JSONField(default=dict)),
                ('route_geojson', models.JSONField(default=dict)),
                ('legs_data', models.JSONField(default=list)),
                ('stops_data', models.JSONField(default=list)),
                ('daily_logs_data', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
                'ordering': ['-created_at'],
            },
        ),
    ]
